// portal/lib/quiz-data.ts

export interface QuizQuestion {
    id: number;
    question: string;
    code?: string;
    options: string[];
    correct: number;
    explanation: string;
    difficulty: 'easy' | 'medium' | 'hard';
}

export interface Quiz {
    id: string;
    lectureId: string;
    title: string;
    description: string;
    timeLimit: number;
    passingScore: number;
    questions: QuizQuestion[];
}

export const QUIZZES: Record<string, Quiz> = {
    '1': {
        id: '1',
        lectureId: '1',
        title: 'Solana Fundamentals Quiz',
        description: 'Test your knowledge of basic Solana concepts',
        timeLimit: 600,
        passingScore: 70,
        questions: [
            {
                id: 1,
                question: 'How many lamports are in 1 SOL?',
                options: ['1,000', '1,000,000', '1,000,000,000', '1,000,000,000,000'],
                correct: 2,
                explanation: '1 SOL = 1,000,000,000 lamports (1 billion).',
                difficulty: 'easy',
            },
            {
                id: 2,
                question: 'Which of these is NOT part of a Solana Account?',
                options: ['lamports', 'data', 'owner', 'password'],
                correct: 3,
                explanation: 'There is no password — security is based on signatures.',
                difficulty: 'easy',
            },
            {
                id: 3,
                question: 'Optimal commitment level for fast and reliable UI?',
                options: ['processed', 'confirmed', 'finalized', 'instant'],
                correct: 1,
                explanation: 'Confirmed is optimal for most dApps.',
                difficulty: 'medium',
            },
            {
                id: 4,
                question: 'How to get balance in SOL?',
                code: 'const b = await connection.getBalance(pk);',
                options: ['b * 10^9', 'b / 10^9', 'b', 'b + 10^9'],
                correct: 1,
                explanation: 'Divide by LAMPORTS_PER_SOL.',
                difficulty: 'easy',
            },
            {
                id: 5,
                question: 'Programs in Solana are...',
                options: ['Stateful — data stored inside', 'Stateless — data in accounts', 'Written in JavaScript', 'Just addresses'],
                correct: 1,
                explanation: 'Solana programs are stateless.',
                difficulty: 'medium',
            },
            {
                id: 6,
                question: 'To send a transaction we need a...',
                options: ['Recent Blockhash', 'Session ID', 'Node password', 'Email'],
                correct: 0,
                explanation: 'Recent blockhash is required.',
                difficulty: 'medium',
            },
            {
                id: 7,
                question: 'What is Devnet?',
                options: ['Main network', 'Test network for development', 'Encryption method', 'Wallet'],
                correct: 1,
                explanation: 'Devnet is a network for testing.',
                difficulty: 'easy',
            },
            {
                id: 8,
                question: 'System Program is responsible for...',
                options: ['NFTs', 'Creating accounts and SOL transfers', 'Voting', 'Staking'],
                correct: 1,
                explanation: 'System Program is the base for accounts and SOL.',
                difficulty: 'easy',
            },
            {
                id: 9,
                question: 'What is Rent in Solana?',
                options: ['Fee for storing data in an account', 'Transaction tax', 'Paid entry to the network', 'Monthly subscription'],
                correct: 0,
                explanation: 'Rent is a fee for storing data in the network state.',
                difficulty: 'medium',
            },
            {
                id: 10,
                question: 'How to become Rent-exempt?',
                options: ['Delete account', 'Keep a minimum balance for 2 years of storage', 'Not possible', 'Be a validator'],
                correct: 1,
                explanation: 'An account becomes rent-exempt if it has enough SOL.',
                difficulty: 'hard',
            },
        ],
    },
    '2': {
        id: '2',
        lectureId: '2',
        title: 'Wallet Integration Quiz',
        description: 'Test your knowledge of wallet integration in React',
        timeLimit: 600,
        passingScore: 70,
        questions: [
            {
                id: 1,
                question: 'Which hook provides access to the wallet?',
                options: ['useWalletAdapter()', 'useWallet()', 'useConnection()', 'useSolana()'],
                correct: 1,
                explanation: 'useWallet is the main hook.',
                difficulty: 'easy',
            },
            {
                id: 2,
                question: 'publicKey will be ... if wallet is not connected',
                options: ['undefined', 'null', '""', 'throws Error'],
                correct: 1,
                explanation: 'PublicKey is null.',
                difficulty: 'easy',
            },
            {
                id: 3,
                question: 'What does autoConnect={true} do?',
                options: ['Creates a wallet', 'Reconnects the last wallet', 'Connects all at once', 'Advertises Phantom'],
                correct: 1,
                explanation: 'Restores the session.',
                difficulty: 'medium',
            },
            {
                id: 4,
                question: 'Which error to catch on user rejection?',
                options: ['404', 'WalletSignTransactionError with "User rejected" message', 'Forbidden', 'Timeout'],
                correct: 1,
                explanation: 'Message "User rejected".',
                difficulty: 'medium',
            },
            {
                id: 5,
                question: 'WalletMultiButton belongs to which library?',
                options: ['@solana/web3.js', '@solana/wallet-adapter-react-ui', '@solana/phantom', 'next-solana'],
                correct: 1,
                explanation: 'UI adapter library.',
                difficulty: 'easy',
            },
            {
                id: 6,
                question: 'Why pass Connection to WalletProvider?',
                options: ['To save memory', 'It is not passed there', 'So hooks have access to RPC', 'For security'],
                correct: 2,
                explanation: 'ConnectionProvider makes connection available via useConnection.',
                difficulty: 'medium',
            },
            {
                id: 7,
                question: 'Can Wallet Adapter be used without React?',
                options: ['Yes', 'No', 'Only in Vue', 'Only in CLI'],
                correct: 0,
                explanation: 'There is a base @solana/wallet-adapter-base.',
                difficulty: 'hard',
            },
            {
                id: 8,
                question: 'PublicKey.toBase58() returns...',
                options: ['Byte array', 'String address', 'Object', 'Hash'],
                correct: 1,
                explanation: 'Base58 is the standard representation for addresses.',
                difficulty: 'easy',
            },
            {
                id: 9,
                question: 'What is a Transaction Instruction?',
                options: ['Description of a single action in a transaction', 'The entire blockchain', 'API documentation', 'A button in UI'],
                correct: 0,
                explanation: 'A transaction consists of one or more instructions.',
                difficulty: 'medium',
            },
            {
                id: 10,
                question: 'Maximum number of signatures in a transaction?',
                options: ['1', 'Unlimited', 'Depends on transaction size (MTU)', '10'],
                correct: 2,
                explanation: 'Limit of ~1232 bytes restricts accounts and signatures.',
                difficulty: 'hard',
            },
        ],
    },
    '3': {
        id: '3',
        lectureId: '3',
        title: 'On-Chain Data Quiz',
        description: 'Test on tokens, NFTs, and Anchor IDL',
        timeLimit: 600,
        passingScore: 70,
        questions: [
            {
                id: 1,
                question: 'Solana token standard is called...',
                options: ['ERC-20', 'SPL Token', 'SOL Token', 'Metaplex'],
                correct: 1,
                explanation: 'SPL stands for Solana Program Library.',
                difficulty: 'easy',
            },
            {
                id: 2,
                question: 'Where is the user token balance stored?',
                options: ['In Mint Account', 'In Associated Token Account (ATA)', 'In Wallet Account', 'In Registry'],
                correct: 1,
                explanation: 'Balance is stored in a separate ATA.',
                difficulty: 'medium',
            },
            {
                id: 3,
                question: 'Library for NFT metadata on Solana?',
                options: ['OpenSea SDK', 'Metaplex', 'Anchor', 'Cargo'],
                correct: 1,
                explanation: 'Metaplex is the standard for NFTs.',
                difficulty: 'easy',
            },
            {
                id: 4,
                question: 'What is Anchor IDL?',
                options: ['Smart contract interface description language', 'Wallet name', 'Token type', 'Rust compiler'],
                correct: 0,
                explanation: 'IDL allows frontend to "understand" the smart contract.',
                difficulty: 'medium',
            },
            {
                id: 5,
                question: 'How to subscribe to account changes?',
                options: ['onAccountChange', 'onChange', 'subscribe', 'watch'],
                correct: 0,
                explanation: 'connection.onAccountChange (WebSocket).',
                difficulty: 'medium',
            },
            {
                id: 6,
                question: 'Token decimal 6 means 1.0 token is...',
                options: ['1 unit', '1,000,000 units', '6 units', '1,000 units'],
                correct: 1,
                explanation: '10^6.',
                difficulty: 'medium',
            },
            {
                id: 7,
                question: 'What does getParsedTokenAccountsByOwner do?',
                options: ['Returns all wallet tokens', 'Creates tokens', 'Burns tokens', 'Changes owner'],
                correct: 0,
                explanation: 'Convenient method for parsing token accounts.',
                difficulty: 'easy',
            },
            {
                id: 8,
                question: 'Which program does Anchor use by default?',
                options: ['System Program', 'SPL Token', 'Anchor is a framework, not a program', 'BpfLoader'],
                correct: 2,
                explanation: 'Anchor is a framework for programs.',
                difficulty: 'easy',
            },
            {
                id: 9,
                question: 'PDA stands for...',
                options: ['Personal Digital Assistant', 'Program Derived Address', 'Public Data Account', 'Private Direct Access'],
                correct: 1,
                explanation: 'PDAs are addresses controlled by a program.',
                difficulty: 'hard',
            },
            {
                id: 10,
                question: 'The owner of an ATA (Associated Token Account) is...',
                options: ['The User', 'Token Program', 'Metaplex', 'System Program'],
                correct: 1,
                explanation: 'The "owner" in Solana sense is the Token Program.',
                difficulty: 'hard',
            },
        ],
    },
    '4': {
        id: '4',
        lectureId: '4',
        title: 'Production Ready Quiz',
        description: 'Final test on optimization and deployment',
        timeLimit: 600,
        passingScore: 70,
        questions: [
            {
                id: 1,
                question: 'Why simulate a transaction?',
                options: ['For aesthetics', 'To catch errors before sending', 'Speeds up network', 'To avoid fees'],
                correct: 1,
                explanation: 'Simulation shows result without broadcasting to network.',
                difficulty: 'easy',
            },
            {
                id: 2,
                question: 'What are Priority Fees?',
                options: ['Tax for the rich', 'Fee to speed up transaction', 'Entry ticket', 'Penalty'],
                correct: 1,
                explanation: 'Allows transaction to land in a block faster.',
                difficulty: 'medium',
            },
            {
                id: 3,
                question: 'Commitment "finalized" guarantees...',
                options: ['Transaction is in network', 'Transaction won\'t be reversed', 'Transaction was fast', 'Balance updated'],
                correct: 1,
                explanation: 'Finalized is the full network confirmation.',
                difficulty: 'medium',
            },
            {
                id: 4,
                question: 'How to optimize 100 balance requests?',
                options: ['None', 'getMultipleAccountsInfo', 'getBalance in a loop', 'Use GraphQL'],
                correct: 1,
                explanation: 'Batching via getMultipleAccountsInfo.',
                difficulty: 'medium',
            },
            {
                id: 5,
                question: 'Where to store private keys on frontend?',
                options: ['localStorage', 'Nowhere — they stay in wallet extension', 'JSON file', 'Cookies'],
                correct: 1,
                explanation: 'Frontend should never see private keys.',
                difficulty: 'easy',
            },
            {
                id: 6,
                question: 'Compute Budget Program allows...',
                options: ['Saving SOL', 'Increasing compute unit limit', 'Buying tokens', 'Deleting account'],
                correct: 1,
                explanation: 'Manages transaction resources.',
                difficulty: 'hard',
            },
            {
                id: 7,
                question: 'What is an RPC Node?',
                options: ['Wallet', 'Gateway to blockchain via API', 'Database', 'Miner'],
                correct: 1,
                explanation: 'Gateway for your dApp.',
                difficulty: 'easy',
            },
            {
                id: 8,
                question: 'Mainnet-beta is...',
                options: ['Test network', 'Real network with real money', 'Alpha version', 'Local network'],
                correct: 1,
                explanation: 'Main Solana network.',
                difficulty: 'easy',
            },
            {
                id: 9,
                question: 'Solana protection against Transaction Replay Attack?',
                options: ['Password', 'Recent Blockhash', 'IP Address', 'Captcha'],
                correct: 1,
                explanation: 'Recent blockhash restricts transaction lifetime.',
                difficulty: 'medium',
            },
            {
                id: 10,
                question: 'Best library to cache RPC data?',
                options: ['Redux', 'React Query / SWR', 'Context API', 'LocalStorage'],
                correct: 1,
                explanation: 'Specific libraries for async data state.',
                difficulty: 'medium',
            },
        ],
    },
};
